### ISSUE TITLE
Fail to install helm-controller (flux-system)

### ISSUE THREAD

**Issue by thatmlopsguy** [glasskube/gitops-template#22]
Running the command 

```sh
glasskube bootstrap git --url https://github.com/thatmlopsguy/kind-gitops-glasskube
```

Give me the following error:

Checking Status of helm-controller (Deployment)  94% |████████████████████████████████████████████████████████████████████████████████████████████████████████████       | (49/52, 5 it/s) [10s:0s]* Couldn't apply manifests: Deployment helm-controller (flux-system) was not ready within the specified timeout: context deadline exceeded

An error occurred during bootstrap:
Deployment helm-controller (flux-system) was not ready within the specified timeout: context deadline exceeded

**Comment by kosmoz** [comment]
Hi @thatmlopsguy, thanks for raising this issue! If possible, please show us the output of `kubectl describe pods -n flux-system -l app=kustomize-controller`.

**Comment by kosmoz** [comment]
> I was able to fix the issue by manually applying the manifests from `bootstrap/glasskube/glasskube.yaml`.

That's great to hear! Don't hesitate to reach out in case you encounter any other issues.
